init model and fake data seeder
tranducquoc/php_blog pull request #3
Opened 2017-12-14 01:54 UTC by tranducquoc

2017-12-14 02:13 UTC, trangkarol reviewed
Anh nên tạo một folder Models để chứa các model.

2017-12-14 02:16 UTC, trangkarol commented on database/seeds/CategoriesTableSeeder.php
> +        DB::table('categories')->insert(['category' => 'Ruby on Rails']);
Anh nên xử dụng factory để tạo seeder anh ơi
https://laravel.com/docs/5.5/seeding#Using Model Factories

2017-12-14 06:56 UTC, trangkarol commented on app/Category.php
> +    protected $fillable = ['category',];
Anh xem convention ở chỗ này rồi fix luôn ạ
https://github.com/framgia/coding-standards/blob/master/vn/php/others.md
Fix những chỗ tương tự luôn anh nhé

2017-12-14 07:15 UTC, huynhquangdiep requested changes
commented

2017-12-14 07:15 UTC, at-diephq commented on app/Post.php
> +      'url',
php indent dùng 4 spaces nhé

2017-12-14 07:15 UTC, at-diephq commented on app/PostTag.php
> +    protected $fillable = ['post_id', 'tag_id', ];
best array => 
```PHP 
$fillable = [
    'post_id', 
    'tag_id',
 ];

2017-12-14 07:15 UTC, at-diephq commented on config/app.php
> +    env('APP_KEY', 'inesindinemwanawabambuyabakoiwe'),
> environment include production, staging, development, testing. So `inesindinemwanawabambuyabakoiwe` is not environment =))

2017-12-14 07:15 UTC, at-diephq commented on database/seeds/DatabaseSeeder.php
> +        CategoriesTableSeeder::class,
using 4 spaces

2017-12-14 07:15 UTC, at-diephq commented on database/seeds/PostTagsTableSeeder.php
> +            DB::table('post_tag')->insert([ //,
` //,` please remove it

2017-12-14 07:15 UTC, at-diephq commented on database/seeds/PostsTableSeeder.php
> +              'category_id' => $faker->numberBetween($min = 1, $max = 3),
This is cheat code. You should select `category_id` from `categories` table. 
` 'category_id' => $faker->randomElement($categoryId ?: $categoryId = App\Category::pluck('id')->toArray()),`

2017-12-20 08:06 UTC, trangkarol commented on database/migrations/2017_12_13_081248_create_post_tags_table.php
> +        Schema::dropIfExists('post_tags');
sao tên table ở relationship lại như vậy anh? Phải đặt là "post_tag" mới đúng anh.
Anh tham khảo ở ttps://laravel.com/docs/5.5/eloquent-relationships#many-to-many

2017-12-20 08:06 UTC, trangkarol commented on database/seeds/DatabaseSeeder.php
> +            PostTagsTableSeeder::class,
Ở đây anh Seed data thiếu User rồi anh ơi

2017-12-27 02:07 UTC, trangkarol commented on app/Models/Tag.php
> +    public function posttags()
Tên funcion là cameCase

2017-12-27 02:11 UTC, merged